

server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: 
        uri: lb://user-service
        predicates:
        - Path=/user/**
      #- id: courseModule
       # uri: lb://course-service
        #predicates:
        #- Path=/course/**
        
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka